// <auto-generated />
using System;
using BudgetR.Server.Infrastructure.Data.BudgetR;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetR.Server.Infrastructure.Data.BudgetR.Migrations
{
    [DbContext(typeof(BudgetRDbContext))]
    partial class BudgetRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountId"));

                    b.Property<long>("AccountTypeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Balance")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(3);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(5);

                    b.Property<string>("LongName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)")
                        .HasColumnOrder(1);

                    b.HasKey("AccountId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_Balance", "[Balance] >= 0");
                        });

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AccountHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.BudgetMonth", b =>
                {
                    b.Property<long>("BudgetMonthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BudgetMonthId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("ExpenseTotal")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(3);

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<decimal>("IncomeTotal")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("MonthYearId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.HasKey("BudgetMonthId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("MonthYearId");

                    b.ToTable("BudgetMonths", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BudgetMonthHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", b =>
                {
                    b.Property<long>("BusinessTransactionActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessTransactionActivityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2);

                    b.Property<string>("ProcessName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(3);

                    b.HasKey("BusinessTransactionActivityId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BusinessTransactionActivities");

                    b.HasData(
                        new
                        {
                            BusinessTransactionActivityId = 1L,
                            CreatedAt = new DateTime(2024, 6, 18, 10, 50, 3, 949, DateTimeKind.Local).AddTicks(9848),
                            ProcessName = "Initial Seeding",
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Expense", b =>
                {
                    b.Property<long>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(2);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)")
                        .HasColumnOrder(1);

                    b.HasKey("ExpenseId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("Expenses", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExpenseHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.ExpenseDetail", b =>
                {
                    b.Property<long>("ExpenseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExpenseDetailId"));

                    b.Property<decimal>("AmountAllocated")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(4);

                    b.Property<long>("BudgetMonthId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("ExpenseId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.HasKey("ExpenseDetailId");

                    b.HasIndex("BudgetMonthId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseDetails", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ExpenseDetailHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.Property<long>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HouseholdId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("HouseholdId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("Households", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("HouseholdHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.HouseholdParameter", b =>
                {
                    b.Property<long>("HouseholdParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HouseholdParameterId"));

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<int?>("HouseholdParameterType")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HouseholdParameterId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("HouseholdParameters");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Income", b =>
                {
                    b.Property<long>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IncomeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(3);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.HasKey("IncomeId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("Incomes", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("IncomeHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.IncomeDetail", b =>
                {
                    b.Property<long>("IncomeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IncomeDetailId"));

                    b.Property<long>("BudgetMonthId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("IncomeId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.HasKey("IncomeDetailId");

                    b.HasIndex("BudgetMonthId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("IncomeId");

                    b.ToTable("IncomeDetails", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("IncomeDetailHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.MonthYear", b =>
                {
                    b.Property<long>("MonthYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MonthYearId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(3);

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("Month")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("MonthYearId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("MonthYears", (string)null);

                    b.HasData(
                        new
                        {
                            MonthYearId = 1L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 2L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 3L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 4L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 5L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 6L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 7L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 8L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 9L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 10L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 11L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 12L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2024
                        },
                        new
                        {
                            MonthYearId = 13L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 14L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 15L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 16L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 17L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 18L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 19L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 20L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 21L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 22L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 23L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 24L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2025
                        },
                        new
                        {
                            MonthYearId = 25L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 26L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 27L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 28L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 29L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 30L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 31L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 32L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 33L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 34L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 35L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 36L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2026
                        },
                        new
                        {
                            MonthYearId = 37L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 38L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 39L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 40L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 41L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 42L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 43L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 44L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 45L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 46L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 47L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 48L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2027
                        },
                        new
                        {
                            MonthYearId = 49L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 50L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 51L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 52L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 53L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 54L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 55L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 56L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 57L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 58L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 59L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 60L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2028
                        },
                        new
                        {
                            MonthYearId = 61L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 62L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 63L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 64L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 65L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 66L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 67L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 68L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 69L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 70L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 71L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 72L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2029
                        },
                        new
                        {
                            MonthYearId = 73L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 74L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 75L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 76L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 77L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 78L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 79L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 80L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 81L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 82L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 83L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 84L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2030
                        },
                        new
                        {
                            MonthYearId = 85L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 86L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 87L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 88L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 89L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 90L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 91L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 92L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 93L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 94L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 95L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 96L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2031
                        },
                        new
                        {
                            MonthYearId = 97L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 98L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 29,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 99L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 100L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 101L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 102L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 103L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 104L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 105L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 106L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 107L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 108L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2032
                        },
                        new
                        {
                            MonthYearId = 109L,
                            IsActive = true,
                            Month = 1,
                            NumberOfDays = 31,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 110L,
                            IsActive = true,
                            Month = 2,
                            NumberOfDays = 28,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 111L,
                            IsActive = true,
                            Month = 3,
                            NumberOfDays = 31,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 112L,
                            IsActive = true,
                            Month = 4,
                            NumberOfDays = 30,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 113L,
                            IsActive = true,
                            Month = 5,
                            NumberOfDays = 31,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 114L,
                            IsActive = true,
                            Month = 6,
                            NumberOfDays = 30,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 115L,
                            IsActive = true,
                            Month = 7,
                            NumberOfDays = 31,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 116L,
                            IsActive = true,
                            Month = 8,
                            NumberOfDays = 31,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 117L,
                            IsActive = true,
                            Month = 9,
                            NumberOfDays = 30,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 118L,
                            IsActive = true,
                            Month = 10,
                            NumberOfDays = 31,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 119L,
                            IsActive = true,
                            Month = 11,
                            NumberOfDays = 30,
                            Year = 2033
                        },
                        new
                        {
                            MonthYearId = 120L,
                            IsActive = true,
                            Month = 12,
                            NumberOfDays = 31,
                            Year = 2033
                        });
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.ReferenceEntities.AccountType", b =>
                {
                    b.Property<long>("AccountTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AccountTypeId"));

                    b.Property<int>("BalanceType")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("AccountTypeId");

                    b.ToTable("AccountTypes", (string)null);

                    b.HasData(
                        new
                        {
                            AccountTypeId = 4L,
                            BalanceType = 0,
                            Name = "Cash"
                        },
                        new
                        {
                            AccountTypeId = 2L,
                            BalanceType = 0,
                            Name = "Savings"
                        },
                        new
                        {
                            AccountTypeId = 1L,
                            BalanceType = 0,
                            Name = "Checking"
                        },
                        new
                        {
                            AccountTypeId = 3L,
                            BalanceType = 1,
                            Name = "Credit Card"
                        },
                        new
                        {
                            AccountTypeId = 5L,
                            BalanceType = 0,
                            Name = "Investment"
                        },
                        new
                        {
                            AccountTypeId = 8L,
                            BalanceType = 0,
                            Name = "Retirement"
                        },
                        new
                        {
                            AccountTypeId = 6L,
                            BalanceType = 1,
                            Name = "Loan"
                        },
                        new
                        {
                            AccountTypeId = 7L,
                            BalanceType = 0,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.FlaggedTransaction", b =>
                {
                    b.Property<long>("FlaggedTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FlaggedTransactionId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(4);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit")
                        .HasColumnOrder(12);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<int>("FlagType")
                        .HasColumnType("int")
                        .HasColumnOrder(11);

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("TransactionBatchId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<long?>("TransactionCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnOrder(5);

                    b.Property<int>("TransactionMonth")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("TransactionYear")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.HasKey("FlaggedTransactionId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("FlaggedTransactions");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.Transaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)")
                        .HasColumnOrder(4);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(10);

                    b.Property<long?>("TransactionBatchId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(9);

                    b.Property<long?>("TransactionCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<DateOnly?>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnOrder(5);

                    b.Property<int>("TransactionMonth")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<int>("TransactionYear")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.HasKey("TransactionId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("TransactionBatchId");

                    b.HasIndex("TransactionCategoryId");

                    b.HasIndex("TransactionMonth", "TransactionYear");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionBatch", b =>
                {
                    b.Property<long>("TransactionBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionBatchId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TransactionBatchId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("TransactionBatches");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionCategory", b =>
                {
                    b.Property<long>("TransactionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionCategoryId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long?>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.HasKey("TransactionCategoryId");

                    b.ToTable("TransactionCategories");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionCategoryRule", b =>
                {
                    b.Property<long>("TransactionCategoryRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionCategoryRuleId"));

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<string>("CategoryRuleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<int>("ComparisonType")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(6);

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Rule")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<long?>("TransactionCategoryId")
                        .HasColumnType("bigint");

                    b.Property<int?>("TransactionType")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.HasKey("TransactionCategoryRuleId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.HasIndex("TransactionCategoryId");

                    b.ToTable("TransactionCategoryRules");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionTypeRule", b =>
                {
                    b.Property<long>("TransactionTypeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TransactionTypeRuleId"));

                    b.Property<int?>("AssignTransactionType")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint");

                    b.Property<int>("ComparisonType")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<long>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumericRule")
                        .HasColumnType("bigint")
                        .HasColumnOrder(2);

                    b.Property<int>("RuleLevel")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<int?>("RuleOnTransactionType")
                        .HasColumnType("int")
                        .HasColumnOrder(7);

                    b.Property<string>("StringRule")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<string>("TransactionTypeRuleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.HasKey("TransactionTypeRuleId");

                    b.HasIndex("BusinessTransactionActivityId");

                    b.ToTable("TransactionTypeRules");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AuthenticationId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(1);

                    b.Property<long?>("BusinessTransactionActivityId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(7);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(2);

                    b.Property<long?>("HouseholdId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(4);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAt");

                    b.Property<long?>("ModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnOrder(8);

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.HasKey("UserId");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UserHistory");
                                ttb
                                    .HasPeriodStart("CreatedAt")
                                    .HasColumnName("CreatedAt");
                                ttb
                                    .HasPeriodEnd("ModifiedAt")
                                    .HasColumnName("ModifiedAt");
                            }));

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            AuthenticationId = "",
                            BusinessTransactionActivityId = 1L,
                            FirstName = "System",
                            IsActive = false,
                            UserType = 0
                        });
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Account", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.ReferenceEntities.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.BudgetMonth", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetR.Server.Domain.Entities.MonthYear", "MonthYear")
                        .WithMany()
                        .HasForeignKey("MonthYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Household");

                    b.Navigation("MonthYear");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.User", "User")
                        .WithOne("BusinessTransactionActivity")
                        .HasForeignKey("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Expense", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.ExpenseDetail", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BudgetMonth", "BudgetMonth")
                        .WithMany()
                        .HasForeignKey("BudgetMonthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Expense", "Expense")
                        .WithMany("ExpenseDetails")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetMonth");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.HouseholdParameter", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Income", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.IncomeDetail", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BudgetMonth", "BudgetMonth")
                        .WithMany()
                        .HasForeignKey("BudgetMonthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Income", "Income")
                        .WithMany("IncomeDetails")
                        .HasForeignKey("IncomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BudgetMonth");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Income");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.MonthYear", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.FlaggedTransaction", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetR.Server.Domain.Entities.Transactions.TransactionCategory", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("Household");

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.Transaction", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetR.Server.Domain.Entities.Transactions.TransactionBatch", null)
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionBatchId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Transactions.TransactionCategory", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId");

                    b.Navigation("Household");

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionBatch", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionCategoryRule", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.HasOne("BudgetR.Server.Domain.Entities.Transactions.TransactionCategory", "TransactionCategory")
                        .WithMany()
                        .HasForeignKey("TransactionCategoryId");

                    b.Navigation("BusinessTransactionActivity");

                    b.Navigation("TransactionCategory");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionTypeRule", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.BusinessTransactionActivity", "BusinessTransactionActivity")
                        .WithMany()
                        .HasForeignKey("BusinessTransactionActivityId");

                    b.Navigation("BusinessTransactionActivity");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.User", b =>
                {
                    b.HasOne("BudgetR.Server.Domain.Entities.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Expense", b =>
                {
                    b.Navigation("ExpenseDetails");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Household", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Income", b =>
                {
                    b.Navigation("IncomeDetails");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.Transactions.TransactionBatch", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BudgetR.Server.Domain.Entities.User", b =>
                {
                    b.Navigation("BusinessTransactionActivity");
                });
#pragma warning restore 612, 618
        }
    }
}
